name: incident-management-backend

services:
    pgsql:
        image: 'postgis/postgis:16-3.4-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-incident_management}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'incident-management-backend-pgsql:/var/lib/postgresql/data'
        networks:
            - backend
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE:-incident_management}'
                - '-U'
                - '${DB_USERNAME:-sail}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'incident-management-backend-redis:/data'
        networks:
            - backend
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    incident-management-backend-pgsql:
        driver: local
    incident-management-backend-redis:
        driver: local
