<?php

declare(strict_types=1);

const CLOVER_REPORT = 'build/logs/clover.xml';
const JUNIT_REPORT = 'build/logs/junit.xml';

/**
 * @param  array<int, string>  $reports
 */
function failAnalysis(string $message, array $reports = []): never
{
    foreach ($reports as $report) {
        if (is_file($report)) {
            @unlink($report);
        }
    }

    fwrite(STDERR, "Analysis coverage failed: {$message}\n");
    exit(1);
}

function loadXmlReport(string $path, string $name): DOMDocument
{
    if (! is_file($path) || filesize($path) === 0) {
        failAnalysis("{$name} report is missing or empty.", [CLOVER_REPORT, JUNIT_REPORT]);
    }

    $previousErrorHandling = libxml_use_internal_errors(true);
    $document = new DOMDocument;
    $loaded = $document->load($path, LIBXML_NONET);
    libxml_clear_errors();
    libxml_use_internal_errors($previousErrorHandling);

    if (! $loaded) {
        failAnalysis("{$name} report is malformed XML.", [CLOVER_REPORT, JUNIT_REPORT]);
    }

    return $document;
}

function requiredIntegerAttribute(DOMElement $element, string $attribute, string $context): int
{
    $value = $element->getAttribute($attribute);

    if ($value === '' || filter_var($value, FILTER_VALIDATE_INT) === false || (int) $value < 0) {
        failAnalysis(
            "{$context} has an invalid {$attribute} metric.",
            [CLOVER_REPORT, JUNIT_REPORT]
        );
    }

    return (int) $value;
}

$reports = [CLOVER_REPORT, JUNIT_REPORT];

if (! is_dir(dirname(CLOVER_REPORT)) && ! mkdir(dirname(CLOVER_REPORT), 0777, true)) {
    failAnalysis('The report directory could not be created.');
}

foreach ($reports as $report) {
    if (is_file($report) && ! unlink($report)) {
        failAnalysis("The stale report {$report} could not be removed.");
    }
}

foreach (['tests/Unit', 'tests/Feature'] as $testDirectory) {
    if (! is_dir($testDirectory)) {
        failAnalysis("Required test directory {$testDirectory} is missing inside the analysis container.", $reports);
    }
}

$startedAt = time();

// Pre-run migrations in a single isolated connection.
// RefreshDatabaseState::migrated is true at suite start (see tests/TestCase.php)
// so RefreshDatabase never runs migrate:fresh — only uses BEGIN/ROLLBACK.
// This avoids PostgreSQL deadlocks with multi-schema DROP TABLE CASCADE when
// the Laravel app connection and the artisan connection share the same database.
$migrateCommand = array_map(
    escapeshellarg(...),
    [PHP_BINARY, 'artisan', 'migrate:fresh', '--force', '--seed']
);

passthru(implode(' ', $migrateCommand), $migrateCode);

if ($migrateCode !== 0) {
    failAnalysis("migrate:fresh exited with status {$migrateCode}.", $reports);
}

$command = array_map(
    escapeshellarg(...),
    [PHP_BINARY, 'artisan', 'test', '--coverage-clover='.CLOVER_REPORT, '--log-junit='.JUNIT_REPORT]
);

passthru(implode(' ', $command), $exitCode);

if ($exitCode !== 0) {
    failAnalysis("PHPUnit exited with status {$exitCode}.", $reports);
}

$junit = loadXmlReport(JUNIT_REPORT, 'JUnit');
$testSuites = $junit->documentElement;

if (! $testSuites instanceof DOMElement || $testSuites->tagName !== 'testsuites') {
    failAnalysis('JUnit does not contain a testsuites root.', $reports);
}

$junitXpath = new DOMXPath($junit);
$suiteNodes = $junitXpath->query('/testsuites/testsuite');

if ($suiteNodes === false || $suiteNodes->length === 0) {
    failAnalysis('JUnit does not contain any test suites.', $reports);
}

$tests = 0;
$assertions = 0;
$failures = 0;
$errors = 0;

foreach ($suiteNodes as $suiteNode) {
    if (! $suiteNode instanceof DOMElement) {
        failAnalysis('JUnit contains an invalid test suite.', $reports);
    }

    $tests += requiredIntegerAttribute($suiteNode, 'tests', 'JUnit test suite');
    $assertions += requiredIntegerAttribute($suiteNode, 'assertions', 'JUnit test suite');
    $failures += requiredIntegerAttribute($suiteNode, 'failures', 'JUnit test suite');
    $errors += requiredIntegerAttribute($suiteNode, 'errors', 'JUnit test suite');
}

if ($tests === 0) {
    failAnalysis('PHPUnit executed zero tests.', $reports);
}

if ($failures !== 0 || $errors !== 0) {
    failAnalysis("JUnit reports {$failures} failures and {$errors} errors.", $reports);
}

$clover = loadXmlReport(CLOVER_REPORT, 'Clover');
$xpath = new DOMXPath($clover);
$coverage = $xpath->query('/coverage')->item(0);
$project = $xpath->query('/coverage/project')->item(0);
$metrics = $xpath->query('/coverage/project/metrics')->item(0);
$files = $xpath->query('/coverage/project//file');
$lines = $xpath->query('/coverage/project//file/line');

if (! $coverage instanceof DOMElement || ! $project instanceof DOMElement) {
    failAnalysis('Clover does not contain the required coverage/project structure.', $reports);
}

$generatedAt = requiredIntegerAttribute($coverage, 'generated', 'Clover coverage');

if ($generatedAt < $startedAt) {
    failAnalysis('Clover was not generated by the current PHPUnit run.', $reports);
}

if (! $metrics instanceof DOMElement || $files === false || $files->length === 0 || $lines === false || $lines->length === 0) {
    failAnalysis('Clover does not contain source files, executable lines, and project metrics.', $reports);
}

$fileCount = requiredIntegerAttribute($metrics, 'files', 'Clover project');
$lineCount = requiredIntegerAttribute($metrics, 'loc', 'Clover project');
$statements = requiredIntegerAttribute($metrics, 'statements', 'Clover project');
$coveredStatements = requiredIntegerAttribute($metrics, 'coveredstatements', 'Clover project');

if ($fileCount === 0 || $lineCount === 0 || $statements === 0) {
    failAnalysis('Clover project coverage metrics are empty.', $reports);
}

printf(
    "Analysis coverage validated: tests=%d assertions=%d failures=0 errors=0 files=%d lines=%d statements=%d covered_statements=%d\n",
    $tests,
    $assertions,
    $fileCount,
    $lineCount,
    $statements,
    $coveredStatements
);
